package yio.tro.antiyoy.stuff;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.files.FileHandle;

/**
 * Reads the build version stamp (the git hash) out of assets/version.txt.
 * That file is generated by the 'generateVersionFile' gradle task on every
 * build - see version.gradle. When it's missing, for instance when the game
 * is launched from an IDE without running the task, the version reads as
 * UNKNOWN_VERSION instead of failing.
 */
public class VersionManager {

    public static final String VERSION_FILE_NAME = "version.txt";
    public static final String UNKNOWN_VERSION = "unknown";

    private static VersionManager instance;
    private String version;


    private VersionManager() {
        version = loadVersion();
    }


    public static VersionManager getInstance() {
        if (instance == null) {
            instance = new VersionManager();
        }

        return instance;
    }


    private String loadVersion() {
        try {
            FileHandle fileHandle = Gdx.files.internal(VERSION_FILE_NAME);
            if (!fileHandle.exists()) return UNKNOWN_VERSION;

            String contents = fileHandle.readString().trim();
            if (contents.length() == 0) return UNKNOWN_VERSION;

            return contents;
        } catch (Exception exception) {
            return UNKNOWN_VERSION;
        }
    }


    public String getVersion() {
        return version;
    }


    /**
     * What's actually shown in the menu, for example "v 07f3422".
     */
    public String getVersionString() {
        return "v " + version;
    }
}
